sudo: required
language: clojure
jdk: oraclejdk8
services:
- docker
deploy:
  provider: script
  script: lein docker-publish
  on:
    all_branches: true
env:
  global:
    secure: Qq+cy+sNb3ZFR09xV1LWgOcB/aQdpc7q6r1ERUsUHus7i+7ajj3CckfOmwy4ClTcqJBOhyOieJdM7KFVpZgui2jHOhOhys5aTV55YhnF0vvq9VNW4ln5xgL0lu6pSp9HienkevDOgzbkOd3ItucHbROxNiw93DEkr64glc51J8tPBzJmgy71T7Ptge1Dwp66sYrtYXYIjcK1PbrMVOIP4Y+lzBZQ8ikEiS0v/I/9vZPEn1KUexqQXOGx+5Sh1e11Y2wyXigCtyRB4J1+SDt32+EIzNmOhSFaSqbKVZ8cExM2hL3UeoPXV+tYBBnX/qMi/s41QNqQ7MlaEp3DkYb0way9LYcyybhiE/90cJdH9pkeU+jgCF/mJjCQX+RwsvWZz+xri4AhM3PCq0CdtA6NdRcU9lcMx+wkAr3fjD75pt0M03wFI84KkBStwbMHfMnEsNtubtrfmTAY6HNE+WKuHjrltiqsA6MZztx7T7sO+yP+4FJbGEG6ctooa3P784+cqLxMIcR2kVwgp5bnK2qNot+voeNrkmfFjn7bpxAGfHm9E9Ly3MrZId60SQpN27IA6t4w2Oy/ZV+o0nmuNWqo3eWszc15s/erwoR0q9yloCbIb8rlNBDMgoz3zPWpTOj3DRsVfLbU5TwCj/htNG0itiH9PE7M1x0gxoikTxNnKIo=
